// <auto-generated />
using System;
using ClashRoyaleApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashRoyaleApi.Migrations
{
    [DbContext(typeof(ClashRoyaleApiContext))]
    partial class ClashRoyaleApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ClashRoyaleApi.Models.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrofeusMinimos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Arena");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.Batalha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoBatalha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrofeusGanhosPerdidos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Batalha");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustoElixir")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiEvolucao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carta");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.CartaJogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCarta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdJogador")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelAtual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiEvolucaoDesbloqueada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeCartas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CartaJogador");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.Cla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdLider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PontosGuerra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoAdesao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrofeusMinimos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cla");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdJogador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDeck")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gemas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ouro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trofeus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("ClashRoyaleApi.Models.ParticipanteBatalha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoroasConquistadas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdBatalha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDeckUsado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdJogador")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParticipanteBatalha");
                });
#pragma warning restore 612, 618
        }
    }
}
